"""Markdown report renderer."""

from __future__ import annotations

from contextlint.models import Report, Severity
from contextlint.rules import get_rule

_SEV_EMOJI = {
    Severity.ERROR: "🔴",
    Severity.WARNING: "🟡",
    Severity.INFO: "🔵",
}


def _fmt(n) -> str:
    if isinstance(n, float):
        return f"{n:g}"
    return str(n)


def render_markdown(report: Report) -> str:
    lines: list[str] = []
    lines.append("# ContextLint Report")
    lines.append("")
    lines.append(f"- **Root:** `{report.root}`")
    lines.append(f"- **Generated:** {report.generated_at}")
    lines.append(f"- **Files analyzed:** {report.files_analyzed}")
    lines.append(f"- **Total chunks:** {report.total_chunks}")
    counts = report.counts_by_severity()
    lines.append(
        f"- **Findings:** {len(report.findings)} "
        f"({counts['error']} error, {counts['warning']} warning, {counts['info']} info)"
    )
    lines.append("")

    _metrics_section(report, lines)
    _cfi_section(report, lines)
    _findings_section(report, lines)

    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append(
        "_Generated by [ContextLint](https://github.com/contextlint/contextlint) — "
        "a fully offline static analyzer for RAG systems. No LLM was called to produce "
        "this report._"
    )
    return "\n".join(lines) + "\n"


def _metrics_section(report: Report, lines: list[str]) -> None:
    stats = report.metrics.get("chunk_stats", {})
    if not stats or not stats.get("count"):
        return
    char = stats.get("char", {})
    token = stats.get("token", {})
    lines.append("## Chunk Statistics")
    lines.append("")
    lines.append("| Metric | Characters | Tokens (est.) |")
    lines.append("| --- | ---: | ---: |")
    for label, key in [
        ("Min", "min"),
        ("Median", "median"),
        ("Mean", "mean"),
        ("P95", "p95"),
        ("Max", "max"),
    ]:
        lines.append(f"| {label} | {_fmt(char.get(key, 0))} | {_fmt(token.get(key, 0))} |")
    lines.append("")
    dup = report.metrics.get("duplicates", {})
    lines.append(f"- **Overlap (consecutive chunks):** {_fmt(stats.get('overlap_pct', 0))}%")
    lines.append(f"- **Duplicate chunks:** {_fmt(dup.get('duplicate_pct', 0))}%")
    lines.append("")


def _cfi_section(report: Report, lines: list[str]) -> None:
    frag = report.metrics.get("fragmentation", {})
    if not frag:
        return
    cfi = frag.get("cfi", 0.0)
    lines.append("## Context Fragmentation Index (experimental)")
    lines.append("")
    lines.append(f"**CFI = {cfi:.3f}** &nbsp; _(0.0 = coherent · 1.0 = fragmented)_")
    lines.append("")
    lines.append(
        f"> ⚠️ Experimental metric. Tracked {frag.get('repeated_entities', 0)} repeated "
        f"entities across {frag.get('entities_tracked', 0)} detected."
    )
    top = frag.get("top_fragmented", [])
    if top:
        lines.append("")
        lines.append("| Entity | Fragmentation | Chunks |")
        lines.append("| --- | ---: | ---: |")
        for item in top:
            lines.append(f"| {item['entity']} | {item['fragmentation']:.3f} | {item['chunks']} |")
    lines.append("")


def _findings_section(report: Report, lines: list[str]) -> None:
    lines.append("## Findings")
    lines.append("")
    if not report.findings:
        lines.append("✅ No issues found. Your context looks clean!")
        lines.append("")
        return
    for finding in report.findings:
        rule = get_rule(finding.rule_id)
        emoji = _SEV_EMOJI.get(finding.severity, "")
        flag = " _(experimental)_" if finding.experimental else ""
        lines.append(
            f"### {emoji} {finding.rule_id} · {rule.name} ({finding.severity.value}){flag}"
        )
        lines.append("")
        lines.append(finding.message)
        lines.append("")
        lines.append(f"**Recommendation:** {finding.recommendation}")
        if finding.locations:
            lines.append("")
            lines.append("<details><summary>Locations</summary>")
            lines.append("")
            for loc in finding.locations:
                lines.append(f"- `{loc.render()}`")
            lines.append("")
            lines.append("</details>")
        lines.append("")
